# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappeditem',
            name='comments',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrappeditem',
            name='votes',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
