# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coindeskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindeskmodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coindeskmodel',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
