# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170523_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMarketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
                ('symbol', models.CharField(max_length=4)),
                ('rank', models.CharField(max_length=2)),
                ('price_usd', models.CharField(max_length=10)),
                ('market_cap_usd', models.CharField(max_length=15)),
                ('percent_change_7d', models.CharField(max_length=6)),
            ],
        ),
    ]
