# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_coinmarketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinmarketmodel',
            name='market_cap_usd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinmarketmodel',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='coinmarketmodel',
            name='name_id',
            field=models.CharField(max_length=20),
        ),
    ]
