# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170529_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinmarketmodel',
            name='price_usd',
            field=models.FloatField(max_length=12),
        ),
    ]
