# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170529_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMarketRecapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_market_recap', models.FloatField(max_length=16)),
                ('btc_dominance', models.FloatField(max_length=6)),
            ],
        ),
    ]
