# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_coinmarketrecapmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarketrecapmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
