# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_coinmarketrecapmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMarketBtcLowHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
