# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_recapmarketnow_recapmarketweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recapmarketnow',
            name='current',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='recapmarketweek',
            name='previous',
            field=models.BigIntegerField(),
        ),
    ]
