# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170602_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinMarketRecapModel',
        ),
        migrations.DeleteModel(
            name='RecapMarketNow',
        ),
        migrations.DeleteModel(
            name='RecapMarketWeek',
        ),
    ]
