# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_coinmarketbtclowhigh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrappedItem',
            new_name='RedditModel',
        ),
    ]
