# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_coinmarketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindeskmodel',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
