# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170605_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=30)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('featured', models.NullBooleanField()),
            ],
        ),
    ]
