# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_newsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='votes',
        ),
    ]
