# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_newsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='featured',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
