# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170605_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinDeskModel',
        ),
        migrations.DeleteModel(
            name='RedditModel',
        ),
    ]
