# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_newsmodel_use_in_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='source',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='category',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
