# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170606_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='category',
            field=models.CharField(max_length=60),
        ),
    ]
